## Site ========================================================================
url: https://choens.github.io/blood-sugars/
name: Blood Sugars
description: An Exploration Of Nightscout CGM Data

# What exactly does this do?
#pages_list:       
#  About: '/about'
#  Blog: '/blog'
#  RSS: '/rss.xml'



## About Me ====================================================================
author: Andy Choens
email: andy.choens@gmail.com
github: Choens



## Config ======================================================================

# Uses kramdown because GitHub told me to.
markdown: rdiscount

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: date

# How many articles do you wish to appear on the front page:
paginate: 7

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]